version: '3.9'
services:

  lidex_app:
    image: lidex:0.3
    command: /opt/conda/bin/python manage.py runserver 0.0.0.0:8008 #/opt/conda/envs/pdal/bin/python
    deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
    volumes:
      - ./coverage:/coverage
      - ./lidex:/app
      - ./output:/output

  lidex_nginx:
    image: nginx:latest
    volumes:
      - ./lidex/static:/app/static
      - ./lidex:/app
      - ./output:/output
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 7080:80
    depends_on:
      - lidex_app
