FROM pdal/pdal:latest
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV HTTPS_PROXY=http://172.20.0.252:3128
ENV HTTP_PROXY=http://172.20.0.252:3128
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
RUN apt-get update && \
    apt-get install -y tzdata && \
    apt-get -y install software-properties-common git && \
    apt-get -y install build-essential cmake g++ && \
    apt-get -y install libboost-all-dev && \
    apt-get -y install cmake-curses-gui && \
    apt-get -y install gcc && \
    apt-get -y install libtbb-dev && \
    apt-get -y install git && \
    apt-get -y install curl
RUN git config --global http.proxy http://172.20.0.252:3128
RUN git config --global https.proxy http://172.20.0.252:3128
RUN git clone https://github.com/m-schuetz/LAStools.git
RUN mkdir /LAStools/LASzip/build
WORKDIR /LAStools/LASzip/build
RUN cmake -DCMAKE_BUILD_TYPE=Release /LAStools/LASzip
RUN make
WORKDIR /
RUN git clone https://github.com/wjakob/tbb.git


RUN git clone https://github.com/potree/PotreeConverter.git
RUN mkdir /PotreeConverter/build
WORKDIR /PotreeConverter/build 
RUN cmake -DCMAKE_BUILD_TYPE=Release -DLASZIP_INCLUDE_DIRS=/home/ubuntu/LAStools/LASzip/dll -DLASZIP_LIBRARY=/home/ubuntu/LAStools/LASzip/build/src/liblaszip.so ..**
RUN make
RUN make install
RUN ln -s /LAStools/LASzip/build/src/liblaszip.so /usr/lib
RUN conda install -y django
RUN conda install -y gunicorn
RUN conda install -y gdal
WORKDIR /app
EXPOSE 8008
