services:

  lidex_configure:
    image: lidex_conf
    command:
      /compile_defaults.sh
    build:
      dockerfile: ./Dockerfile_conf
    env_file:
      - .env
    volumes:
      - .env:/env
      - ./compile_defaults.sh:/compile_defaults.sh
      - ./wegue_custom_app/wegue_custom/static:/defaults

  lidex_webapp:
    image: lidex_webapp:latest
    build:
      context: .
    command: /opt/conda/bin/python manage.py runserver 0.0.0.0:8008 #/opt/conda/envs/pdal/bin/python
    env_file:
      - .env
    deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
    volumes:
      - ./data/coverage:/coverage
      - ./lidex:/app
      - ./data/output:/output

  lidex_webgis_dev:
    image: lidex_frontend_dev:latest
    build:
      context: ./wegue_custom_app
    env_file:
      - .env
    volumes:
      - .env:/env
      - ./wegue_custom_app/wegue_custom:/app/app
    ports:
      - 8087:8081
    depends_on:
      - lidex_webapp

  lidex_qgisserver:
    image: lidex_qgis:latest
    build:
      context: ./build_qgis
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./data/services/plugins:/plugins

  lidex_nginx:
    image: lidex_nginx:latest
    build:
      context: ./build_nginx
    env_file:
      - .env
    volumes:
      - ./lidex/static:/app/static
      - ./data/output:/output
      - ./nginx_80_template.conf:/etc/nginx/conf.d/default.conf.template
    ports:
      - 80:80
    depends_on:
      - lidex_webapp
      - lidex_qgisserver
      - lidex_webgis_dev

  lidex_test_nginx:
    image: lidex_nginx:latest
    env_file:
      - .env
    volumes:
      - ./lidex/static:/app/static
      - ./data/output:/output
      - ./nginx_8080_template.conf:/etc/nginx/conf.d/default.conf.template
    ports:
      - 8080:8080
    depends_on:
      - lidex_webapp
