version: '3.9'
services:

  lidex:
    image: lidex:latest
    command: /opt/conda/bin/python manage.py runserver 0.0.0.0:8008 #/opt/conda/envs/pdal/bin/python
    deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
    volumes:
      - ./coverage:/coverage
      - ./lidex_app:/app
      - ./output:/output

  nginx:
    image: nginx:latest
    volumes:
      - ./lidex_app/static:/app/static
      - ./lidex_app:/app
      - ./output:/output
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1337:80
    depends_on:
      - lidex